ssh_key_name: my_public_ssh_key_tf
aws_region: us-east-1
vpc_name: Data-Center-CA
# This must be unique at aws
my_s3_bucket_name: demo-datacenter-451-eca
tf_config_files:
  - main.tf
  - backend.tf
  - data.tf
  - terraform.tf
  - variables.tf
  - win25_userdata_nopasswd
ansible_python_interpreter: /usr/bin/python3
