---
- name: Stuff we are always going to do
  tags:
    - always
  block:

    - name: Check to see if terraform is in the path
      register: terraform_path
      changed_when: false
      ansible.builtin.command: terraform version

    - name: If terraform_path.rc != 0, let the user know that terraform isn't installed and exit
      when: terraform_path.rc != 0
      ansible.builtin.fail:
        msg: Terraform isn't installed. Please install Terraform before proceeding.

    # fail with good error for Automation controller user
    - name: Determine that both AAP and Machine credentials are set
      ansible.builtin.assert:
        that:
          - "lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') !=''"
          - "lookup('ansible.builtin.env', 'CONTROLLER_HOST') !=''"
          - "lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') !=''"
        fail_msg:
          - "Red Hat Ansible Automation Platform credential is not set"
          - "Please assign correct credentials to the Job Template"

    - name: Create a new token
      ansible.platform.token:
        aap_hostname: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
        aap_username: "{{ lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') }}"
        aap_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
        aap_validate_certs: false
        description: Demo Datacenter infrastructure
        scope: write
        state: present

- name: Provision our infrastructure
  tags:
    - create
  block:

    - name: Grab vault from remote url
      ansible.builtin.get_url:
        url: '{{ my_remote_vault }}'
        dest: "{{ playbook_dir }}/remotevault.yml"
        mode: '0644'

    - name: Create an S3 bucket for out main.tf
      amazon.aws.s3_bucket:
        region: "{{ aws_region }}"
        name: "{{ my_s3_bucket_name }}"
        state: present

    - name: Include the files needed to destroy the infrastructure
      ansible.builtin.include_vars:
        file: files/tf_files.yml

    - name: Files we care about
      loop:
        - "files/variables.tf"
        - "files/terraform.tf"
        - "files/win25_userdata_nopasswd"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ playbook_dir }}/{{ item | ansible.builtin.basename }}"
        mode: '0644'

    - name: Templates we care about
      loop: "{{ files }}"
      ansible.builtin.template:
        src: templates/{{ item['template'] }}
        dest: "{{ playbook_dir }}/{{ item['name'] }}"
        force: true
        mode: '0644'

    - name: PUT Terraform config files into s3
      loop: "{{ tf_config_files }}"
      amazon.aws.s3_object:
        bucket: "{{ my_s3_bucket_name }}"
        object: development/{{ item }}
        src: "{{ playbook_dir }}/{{ item }}"
        mode: put

    - name: Deploy hosts to AWS
      register: tf_hosts_result
      community.general.terraform:
        project_path: "{{ playbook_dir }}"
        force_init: true
        state: present

    - name: Debug terraform apply
      when: debug | default(false)
      ansible.builtin.debug:
        var: tf_hosts_result

    - name: Create a zip archive of a directory
      community.general.archive:
        path: "{{ playbook_dir }}/.terraform" # The directory you want to zip
        dest: "{{ playbook_dir }}/terraform.zip" # The destination path and filename for the zip file
        format: zip

    - name: PUT my archived /.terraform/providers/ into s3
      amazon.aws.s3_object:
        bucket: "{{ my_s3_bucket_name }}"
        object: development/terraform.zip
        src: "{{ playbook_dir }}/terraform.zip"
        mode: put

    - name: Refresh my inventory
      ansible.controller.inventory_source_update:
        name: running
        inventory: "Demo Datacenter"
        organization: "IT Service Automation"
        wait: true

    - name: Update existing group
      ansible.controller.group:
        controller_host: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
        controller_oauthtoken: "{{ ansible_facts['aap_token']['token'] }}"
        validate_certs: false
        name: ad
        inventory: "Demo Datacenter"
        preserve_existing_hosts: true
        variables:
          ansible_connection: winrm
          ansible_winrm_transport: credssp
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5986
          ansible_winrm_operation_timeout_sec: 180
          ansible_winrm_read_timeout_sec: 240

    - name: Remove my token
      ansible.platform.token:
        aap_hostname: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
        existing_token: "{{ ansible_facts['aap_token'] }}"
        aap_token: "{{ ansible_facts['aap_token']['token'] }}"
        aap_validate_certs: false
        state: absent

- name: Destroy our infrastructure
  tags:
    - remove
  block:

    - name: Include the files needed to destroy the infrastructure
      ansible.builtin.include_vars:
        file: files/s3_files.yml

    - name: Get my files from my s3 bucket
      loop: "{{ s3_files }}"
      amazon.aws.s3_object:
        bucket: "{{ my_s3_bucket_name }}"
        object: "{{ item['object'] }}"
        dest: "{{ playbook_dir }}/{{ item['name'] }}"
        mode: get

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ playbook_dir }}/.terraform"
        state: directory
        mode: '0700'

    - name: Extract providers
      ansible.builtin.unarchive:
        src: "{{ playbook_dir }}/terraform.zip"
        dest: "{{ playbook_dir }}/"

    - name: Destroy hosts in AWS
      register: tf_hosts_result
      community.general.terraform:
        project_path: "{{ playbook_dir }}"
        force_init: true
        state: absent
        init_reconfigure: true

    - name: Debug terraform apply
      when: debug | default(false)
      ansible.builtin.debug:
        var: tf_hosts_result

    - name: Remove my S3 bucket for out main.tf
      amazon.aws.s3_bucket:
        region: "{{ aws_region }}"
        name: "{{ my_s3_bucket_name }}"
        force: true
        state: absent

    - name: Refresh my inventory
      ansible.controller.inventory_source_update:
        name: running
        inventory: "Demo Datacenter"
        organization: "IT Service Automation"
        wait: true

    - name: Remove my token
      ansible.platform.token:
        aap_hostname: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
        existing_token: "{{ ansible_facts['aap_token'] }}"
        aap_token: "{{ ansible_facts['aap_token']['token'] }}"
        aap_validate_certs: false
        state: absent
