---
s3_files:
  - name: terraform.zip
    object: development/terraform.zip
  - name: terraform.tfstate
    object: development/terraform.tfstate
  - name: main.tf
    object: development/main.tf
  - name: backend.tf
    object: development/backend.tf
  - name: data.tf
    object: development/data.tf
  - name: variables.tf
    object: development/variables.tf
  # - name: win25_userdata_nopasswd
  #   object: development/win25_userdata_nopasswd