---
- name: Manage Red Hat Registration
  hosts: satellite

  tasks:

    - name: Include the redhat subscription manager role
      tags:
        - remove
      ansible.builtin.include_role:
        name: rhsm

- name: Manage datacenter
  hosts: localhost
  connection: local

  tasks:

    - name: Include the infrastructure role
      tags:
        - create
      ansible.builtin.include_role:
        name: infrastructure

    - name: Include the infrastructure role
      tags:
        - remove
      ansible.builtin.include_role:
        name: infrastructure
