---
- name: Provision demo datacenter
  hosts: localhost
  connection: local
  vars:
    machine:
      password: '{{ ansible_password }}'

  tasks:

    - name: Debug
      tags:
        - create
      ansible.builtin.debug:
        var: ansible_password

    - name: Include the infrastructure role
      tags:
        - create
      ansible.builtin.include_role:
        name: infrastructure

    - name: Include the infrastructure role
      tags:
        - remove
      ansible.builtin.include_role:
        name: infrastructure
