---
- name: Register Satellite server with redhat
  hosts: satellite

  tasks:

    - name: Grab vault from remote url
      tags:
        - create
      ansible.builtin.get_url:
        url: '{{ my_remote_vault }}'
        dest: files/remotevault.yml
        mode: '0644'

    - name: Include configurations
      tags:
        - create
      ansible.builtin.include_vars:
        file: files/remotevault.yml

    - name: Include the redhat subscription manager role
      tags:
        - create
      ansible.builtin.include_role:
        name: rhsm

    - name: Include the redhat subscription manager role
      tags:
        - remove
      ansible.builtin.include_role:
        name: rhsm
